### ISSUE TITLE
Illustration of a MiniApp page

### ISSUE THREAD

**Issue by xfq** [w3c/miniapp-white-paper#3]
Because the concept of a [page](https://w3c.github.io/miniapp-packaging/#dfn-page) in a MiniApp is not exactly the same as that of the web, it would be more intuitive to have a picture to indicate what a page in a MiniApp is.

**Comment by espinr** [comment]
Good point @xfq , 
I created this picture in the past. 

Edit: I'm linking [the version we discussed ](https://github.com/w3c/miniapp-packaging/commit/cf1dfe3b9fe494b175a07f108e757ac007018411) here, because I rewrote the diagram (and the new version was shown here).

Please MiniApp vendors, have a look and suggest changes if needed. Based on this picture, we also need to clarify the concept of _component_. Or just using another term?

**Comment by xfq** [comment]
Is it possible that multiple pages share the same CSS (such as the general theme for the MiniApp) or share the same component (such as a list component)?

**Comment by espinr** [comment]
> Is it possible that multiple pages share the same CSS (such as the general theme for the MiniApp) or share the same component (such as a list component)?

Yes, I've tried to represent it on the same diagram with also some examples of shared resources (image and stylesheets). What about this?

![MiniApp components representation](https://w3c.github.io/miniapp-packaging/images/miniapp-pages-components.svg)

Suggestions for improving the diagram are welcome. Thanks!

**Comment by xfq** [comment]
LGTM. Thank you!

**Comment by espinr** [comment]
I've created a new section with the image to introduce the components, pages and resources. It's very brief, but enough to describe the image. Small changes in the next section to make both sections complementary.

The new section is at
https://raw.githack.com/espinr/miniapp-white-paper/miniapp-image/index.html#sec-miniapp-pages-components
